apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-app
spec:
  project: default
  source:
    repoURL: https://github.com/pawelkuk/manifests.git
    targetRevision: HEAD
    path: prometheus

    kustomize:
      version: v3.5.4
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
